### ISSUE TITLE
Replace key/vault access in Metrics resources with Managed Identity

### ISSUE THREAD

**Issue by echappen** [18F/piipan#333] opened 2021-02-09 18:54 UTC
I know it's already been discussed, but just noting the future work to implement the use of a managed identity (or system-assigned identity) for connecting directly to the database without the need for getting/storing secrets with key vault.

_Originally posted by @kingcomma in https://github.com/18F/piipan/pull/298#discussion_r573088872_

**Comment by kingcomma** [comment] 2021-06-25 17:25
@cjhskippy This appears to be a duplicate of #409. I'm closing for now, but happy to reopen if I'm mistaken.

**Closed by kingcomma** 2021-06-25 17:25 UTC
